// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeletlenVacsora.Data;

namespace VeletlenVacsora.Data.Migrations
{
    [DbContext(typeof(VacsoraDbContext))]
    [Migration("20210102124205_RecepieIsOnMenu_Modified_2_RecepieOnMenu")]
    partial class RecepieIsOnMenu_Modified_2_RecepieOnMenu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("VeletlenVacsora.Data.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("VeletlenVacsora.Data.Models.IngredientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IngredientTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PackageTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientTypeId");

                    b.HasIndex("PackageTypeId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("VeletlenVacsora.Data.Models.RecepieIngredientModel", b =>
                {
                    b.Property<int>("RecepieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.HasKey("RecepieId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecepieIngredients");
                });

            modelBuilder.Entity("VeletlenVacsora.Data.Models.RecepieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OnMenu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recepies");
                });

            modelBuilder.Entity("VeletlenVacsora.Data.Models.IngredientModel", b =>
                {
                    b.HasOne("VeletlenVacsora.Data.Models.CategoryModel", "IngredientType")
                        .WithMany()
                        .HasForeignKey("IngredientTypeId");

                    b.HasOne("VeletlenVacsora.Data.Models.CategoryModel", "PackageType")
                        .WithMany()
                        .HasForeignKey("PackageTypeId");

                    b.Navigation("IngredientType");

                    b.Navigation("PackageType");
                });

            modelBuilder.Entity("VeletlenVacsora.Data.Models.RecepieIngredientModel", b =>
                {
                    b.HasOne("VeletlenVacsora.Data.Models.IngredientModel", "Ingredient")
                        .WithMany("Recepies")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeletlenVacsora.Data.Models.RecepieModel", "Recepie")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecepieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recepie");
                });

            modelBuilder.Entity("VeletlenVacsora.Data.Models.RecepieModel", b =>
                {
                    b.HasOne("VeletlenVacsora.Data.Models.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VeletlenVacsora.Data.Models.IngredientModel", b =>
                {
                    b.Navigation("Recepies");
                });

            modelBuilder.Entity("VeletlenVacsora.Data.Models.RecepieModel", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
